name: "React Native CI"
description: "Realiza el lint, build, test and coverage"
inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ''
  sdk_platform:
    required: false
    description: "SDK Platform"
    default: "31"
  build_tools: 
    required: false
    description: "Build tools"
    default: "31.0.0"
  sdk_tools:
    required: false
    description: "SDK Build tools"
    default: "7583922_latest"
  emulator_version:
    required: false
    description: "Emulator version"
    default: "30.7.5"
  java_version:
    required: false
    description: "Emulator version"
    default: "11"

runs:
  using: "composite"
  
  steps:
    - name: Use Node.js ${{ inputs.matrix_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Generate .npmrc file
      uses: architecture-it/actions@generate-npmrc
      with:
        npm_token: ${{ inputs.packages_token }}
        font_awesome_key: ${{ inputs.fontawesome_token }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
    - name: Set up Android SDK and build tools
      uses: android-actions/setup-android-sdk@v2
      with:
        sdk-platform: ${{ inputs.sdk_platform }}
        build-tools: ${{ inputs.build_tools }}
        sdk-tools: ${{ inputs.sdk_tools }}
        emulator-version: ${{ inputs.emulator_version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash


