name: "SonarQube Pre-requisitos"
description: "Se realiza la configuración de los proyectos en sonarqube, se deben realizar a mano hasta que exista el endpoint de import from github"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
  sonar_key:
    description: "Key del repositorio"
    required: true
  alm_setting :
    description: "config alm github settings"
    required: false
    default: 'GitHubGLA'
  alm_setting_monorepo :
    description: "config alm github settings monorepo"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: "Create Project"
      run: |
        curl -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/projects/create' -d name=${{ inputs.sonar_key }} -d project=${{ inputs.sonar_key }}
      shell: bash 
    - name: "Rename Branch default"
      run: |
        curl -s -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/project_branches/rename' -d project=${{ inputs.sonar_key }} -d name=${{ github.event.repository.default_branch }} -D- -o /dev/null -w %{http_code} > http.txt
      shell: bash 
    - name: "Analisis rename branch"
      id: rename
      run: |
        cat http.txt
        if grep -q "204" http.txt;
        then
          echo "Todo OK"
          echo "::set-output name=OUTPUT::0"
        else 
          echo "la branch no se seteo por defecto se eliminara la branch para definir la nueva por defecto"
          echo "::set-output name=OUTPUT::1"
        fi
      shell: bash
    - name: "Delete and Rename branch"
      run: |
          curl -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/project_branches/delete' -d project=${{ inputs.sonar_key }} -d branch=${{ github.event.repository.default_branch }}
          curl -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/project_branches/rename' -d project=${{ inputs.sonar_key }} -d name=${{ github.event.repository.default_branch }}
      if: steps.rename.outputs.OUTPUT == 1
      shell: bash
    - name: "Set ALM Setting binding"
      run: |
        curl -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/alm_settings/set_github_binding' -d almSetting=${{ inputs.alm_setting }} -d monorepo=${{ inputs.alm_setting_monorepo }} -d project=${{ inputs.sonar_key }} -d repository=${{ github.event.repository.full_name }}
      shell: bash
