name: "Update an issue in Repository"
description: "Realiza un comentario y cierra el Issue"

inputs:
  issueId:
    description: 'ID de la issue a actualizar'
    required: true


runs:
  using: "composite"
  steps:

    - name: Comment and CLose
      uses: actions/github-script@v7
      with:
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Date in format and in argentina
          const date = new Date().toLocaleString('es-AR', { timeZone: 'America/Argentina/Buenos_Aires' });

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: inputs.issueId,
            body: `
            Restart Service realizado con éxito 🚀

            Realizado con éxito el ${date}
            `
          });

          // Close Issue"
          await github.rest.issues.update({
            owner,
            repo,
            issue_number: inputs.issueId,
            state: 'closed'
          });

          `;
    