name: "Create avro schema"
description: "Se realiza el análisis en sonarqube para NET"
inputs:
  file_idl:
    description: "file idl with record to convert in avro"
    required: true
runs:
  using: "composite"
  steps:
      env:
        AVRO_VERSION: 1.11.0
        AVRO_MIRROR: https://apache.zero.com.ar/avro
        OUTPUT: "schema"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jre # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Create Folder
        run: mkdir ${{ env.OUTPUT }}
        shell: bash
      - name: Get Avro Tools
        run: wget --quiet ${{env.AVRO_MIRROR}}/avro-${{env.AVRO_VERSION}}/java/avro-tools-${{env.AVRO_VERSION}}.jar
        shell: bash
      - name: Generate Schema Protocol
        run: java -jar avro-tools-${{env.AVRO_VERSION}}.jar idl2schemata ${{ inputs.SOURCE_EVENTS_FILE_IDL }} ${{ env.OUTPUT }}/schemas.avpr
        shell: bash
      - name: Generate Schema Classes 
        run: java -jar avro-tools-${{env.AVRO_VERSION}}.jar idl ${{ inputs.SOURCE_EVENTS_FILE_IDL }} ${{ env.OUTPUT }}
        shell: bash
      - name: Archive schema avro result
        uses: actions/upload-artifact@v1
        with:
          name: avro-schema
          path: ${{ env.OUTPUT }}