name: "Dotnet build and test"
description: "Realiza el Restore, build y test"
inputs:
  workdir_src:
    description: "directorio donde se encuentra el cproj a compilar DEFAULT: ./"
    required: false
    default: './'
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./"
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./main.go
      working-directory: ${{ inputs.workdir_src }}

    #- name: Test
    #  run: go test ./... -cover
    #  working-directory: ${{ inputs.workdir_test }}