name: "Release basic"
description: "Make a Release on conventional commits"

inputs:
  github_token:
    description: Github Token
    required: true
  branches:
    description: configuration to latest release and prerelease
    default: '["main", { name: "beta", prerelease: "beta" }]'
    required: false
  github_username: 
    description: github user 
    required: true
  release_assets:
    default: '["dist/**"]'
    required: false
    description: Glob patterns to find assets paths.
  draft:
    default: 'false'
    required: false
    description: Create a draft release

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
    - name: Write configuration file
      shell: bash
      run: |
        echo 'module.exports = {
          plugins: [
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            [
              "@semantic-release/github",
              {
                "assets": ${{ inputs.release_assets }}
                "draftRelease": ${{ inputs.draft }}
              }
            ]
          ],
          branches: ${{ inputs.branches }}
        }' >> release.config.cjs
    - name: Install dependencies
      # with '--no-save' flag not generates any files (only generated for pipeline)
      run: npm i --no-save @semantic-release/github
      shell: bash
    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
        NUGET_PUSH_URL: "github"
        NUGET_TOKEN: ${{ inputs.github_token }}
      run: npx semantic-release
      shell: bash
