name: "React Prepare"
description: "Realiza la configuración necesaria e install de las dependencias(npm, yarn, pnpm)"

inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ''
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
  ci:
    description: "Esta variable forza el chequeo del linter y en caso de fallas rompe el flujo"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Get package manager of Repo
      run: |
        if [ -f "yarn.lock" ]; then 
          echo "name=yarn" >> $GITHUB_OUTPUT
        elif [ -f "package-lock.json" ]; then 
          echo "name=npm" >> $GITHUB_OUTPUT 
        elif [ -f pnpm-lock.yaml ]; then 
          echo "name=pnpm" >> $GITHUB_OUTPUT 
        else 
          echo "name=notfound" >> $GITHUB_OUTPUT  
        fi
      id: package_manager
      shell: bash
    - name: validate 'Lockfile'
      if: ${{ steps.package_manager.outputs.name == 'notfound' }}
      run: |
        echo "El código debe contener algún archivo de lockfile ('package-lock.json', 'yarn.lock' o 'pnpm-lock.yaml')."
        echo "Asegurate de subirlo."
        echo "ERROR: Falta archivo lockfile. Ver más en https://architecture-it.github.io/docs/Platform/Front/#manejo-de-dependencias"
        exit 1
      shell: bash    
    - name: config npmrc file fontawesome 
      if: ${{ inputs.fontawesome_token != '' }}
      run: |
        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
        echo '//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome_token }}' >> .npmrc
      shell: bash
    - name: config npmrc file github packages of company
      if: ${{ inputs.packages_token != '' }}
      run: |
        echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '@operations-innovation:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '//npm.pkg.github.com/:_authToken=${{ inputs.packages_token }}' >> .npmrc
      shell: bash
    - name: Enable config for pnpm
      if: ${{ steps.package_manager.outputs.name == 'pnpm' }}
      run: |
        echo 'auto-install-peers=true' >> .npmrc
        echo 'enable-pre-post-scripts=true' >> .npmrc
      shell: bash
    - name: Use pnpm Setup
      if: ${{ steps.package_manager.outputs.name == 'pnpm' }}
      uses: pnpm/action-setup@v2
      with:
        version: 8
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ steps.package_manager.outputs.name }}
    - name: Install dependencies
      run: |
        if [ -f yarn.lock ]; then 
          yarn --frozen-lockfile
        elif [ -f package-lock.json ]; then
          npm ci --no-progress --loglevel error
        elif [ -f pnpm-lock.yaml ]; then
          pnpm install --frozen-lockfile
        fi
      shell: bash
