name: "Update an issue in Repository"
description: "Realiza un comentario y cierra el Issue"

inputs:
  issue_id:
    description: 'ID de la issue a actualizar'
    required: true
  github_token:
    description: 'Token de GitHub'
    required: true


runs:
  using: "composite"
  steps:

    - name: Comment and CLose
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          const issue_number = core.getInput('issue_id');

          // Date in format and in argentina
          const date = new Date().toLocaleString('es-AR', { timeZone: 'America/Argentina/Buenos_Aires' });

          const body = `
          Restart Service realizado con éxito 🚀

          Realizado con éxito el ${date}
          `;
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body
          });

          // Close Issue
          await github.rest.issues.update({
            owner,
            repo,
            issue_number,
            state: 'closed'
          });

    