name: "React CI"
description: "Realiza el lint, build, test and coverage"
inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  github_token: 
    description: "github token"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: true
  packages_token:
    description: "token github para autenticarse en packages"
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate .npmrc file
      env:
        NPM_CUSTOMER_EXP_TOKEN: ${{ inputs.packages_token }}
        NPM_FONTAWESOME_TOKEN: ${{ inputs.fontawesome_token }}
      run: |
        echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '//npm.pkg.github.com/:_authToken=$NPM_CUSTOMER_EXP_TOKEN' >> .npmrc
        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
        echo '//npm.fontawesome.com/:_authToken=$NPM_FONTAWESOME_TOKEN' >> .npmrc
      shell: bash
    - name: Use Node.js ${{ inputs.matrix_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --no-audit --silent
      shell: bash
    - name: Build
      run: npm run build --if-present
      shell: bash
    - run: npm test
      name: Unit tests
      shell: bash
    - name: Coverage
      uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
      with:
        github-token: ${{ inputs.github_token }}
        threshold: 50 # optional parameter\
        skip-step: install