name: "Dotnet build and test"
description: "Realiza el Restore, build y test"
inputs:
  workdir_src:
    description: "directorio donde se encuentra el cproj a compilar DEFAULT: ./"
    required: false
    default: './'
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./"
    required: false
    default: './'
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
  go_version:
    description: "Versión de Go a instalar para el build"
    required: false
    default: 'stable' 

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go_version }}

    - run: go version
      shell: bash

    - name: Build
      run: go build -v ./main.go
      shell: bash
      working-directory: ${{ inputs.workdir_src }}
        
    - name: Test
      run: |
        go test ./... -coverprofile=coverage.out
      shell: bash
      working-directory: ${{ inputs.workdir_test }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{ inputs.workdir_test }}/coverage.out
      if: ${{ inputs.skip_test != 'true' }}
