name: "Release npm"
description: "Realiza el release basado en los commits y conventional commit"
inputs:
  publish:
    description: "Publish to internal modules"
    required: false
    default: "false"
  github_token:
    description: Github Token
    required: true
  branches:
    description: configuration to latest release and prerelease
    default: '["cicd", { name: "main", prerelease: "development" }]'
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Write configuration file
      shell: bash
      run: |
        echo 'module.exports = { plugins: ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", ["@semantic-release/npm",{  "npmPublish": ${{ inputs.publish }},}],"@semantic-release/github",["@semantic-release/exec",{  prepareCmd: "npx rjp package.json version ${nextRelease.version}",},],["@semantic-release/git",{  message: "Release <%= nextRelease.version %> [skip ci]",  assets: ["package.json"],},],],branches: ${{ inputs.branches }} }' >> release.config.js
    - name: Install dependencies
      run: npm i --no-save replace-json-property@1.8.0 @semantic-release/exec @semantic-release/git @semantic-release/github
      shell: bash
    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
      run: npx semantic-release
      shell: bash

