name: "Validate PR Format"
description: "Realiza la validacion del formato del PR"
inputs:
  github_token:
    description: Github Token
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Name of commits title and branch name
      id: get_pr_name
      run: |
        pr_name=$(jq -r .pull_request.title $GITHUB_EVENT_PATH)
        branch_name=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)
        commits_messages=$(jq -r '.commits[].message' $GITHUB_EVENT_PATH)
        echo "pr_name=$pr_name" >> $GITHUB_ENV
        echo "branch_name=$branch_name" >> $GITHUB_ENV
        echo "commits_messages=$commits_messages" >> $GITHUB_ENV
      shell: bash

    - name: Validate Format
      id: validate_format
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { pr_name, branch_name, commits_messages } = process.env;


          const regexOfIssue = /^.*?[A-Z0-9-]+.*$/g;
          const regexConventionCommit = /^(feat|fix)\:\s.*$/g;

          const branchName = branch_name.replace(/refs\/heads\//, '');


          // JIRA VALIDATIONS
          const isValidTitleOfPRForJira = pr_name.match(/^(feat|fix)\([A-Z0-9-]+\)\:\s.*$/);

          const isValidBranchNameForJira = branchName.match(regexOfIssue);
          
          const willTriggerNewVersion = pr_name.match(regexConventionCommit);

          const anyJiraIntegrationValid = isValidTitleOfPRForJira || isValidBranchNameForJira;

          const body = `
          <details>
          <summary> Convención de commits ${willTriggerNewVersion ? ':white_check_mark:' : ':x:'} </summary>
          
          - Disparará una nueva versión: ${willTriggerNewVersion ? ':heavy_check_mark:' : ':exclamation:'}.
            Si deseas que dispare una nueva versión debe seguir el siguiente formato: '(feat|fix): message'. Ver más en [Documentación](https://www.conventionalcommits.org/en/v1.0.0/)
          </details>

          <details>
            <summary> Integración con JIRA ${anyJiraIntegrationValid ? ':white_check_mark:' : ':x:'} </summary>

            - Título del Pull Request: ${isValidTitleOfPRForJira ? ':heavy_check_mark:' : ':exclamation:'}
            - Nombre del branch: ${isValidBranchNameForJira ? ':heavy_check_mark:' : ':exclamation:'}

            Ver más en [Documentación](https://architecture-it.github.io/docs/Onboarding/jira/)

          </details>

          <details>
            <summary> Detalles </summary>
            - Título del Pull Request: ${pr_name}
            - Nombre del branch: ${branchName}
            - Mensajes de los commits: ${commits_messages}
          </details>

          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body,
          });

    