name: "Python CI"
description: "Realiza build, test y coverage para proyectos Python"
inputs:
  version:
    description: "Versión de Python, ej. 3.7, 3.8..."
    required: true
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false'
  # Directories
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./"
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage
      shell: bash

    # - name: Validate build
    #   run: |
    #     python -m compileall -f .  
    #   shell: bash

    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ inputs.workdir_test }}src
      run: |
        coverage run -m unittest discover -s test/. -p "*.py"
        coverage report
        coverage xml
      shell: bash
      working-directory: ${{ inputs.workdir_test }}

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ${{ inputs.workdir_test }}/coverage.xml
      if: ${{ inputs.skip_test != 'true' }}
