name: "Sonar Analizer Javascript/Typescript"
description: "Realiza el análisis de sonarqube para Javascript/Typescript"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
  sonar_key:
    description: "Key del repositorio"
    required: true
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
  verbose:
    description: "The run of sonnarqube will be in verbose mode"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
          path: coverage
        if: ${{ inputs.skip_test != 'true' }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3.1.0
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
          SONAR_HOST_URL: ${{ inputs.sonar_url }}
          LC_ALL: "ru_RU.UTF-8"
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar_key }}
            -Dsonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=**/coverage/lcov.info
            -Dsonar.verbose=${{ inputs.verbose }}
