name: "Create an issue in Repository"
description: "Registra las ocaciones en las que se reinicia un servicio"

inputs:
  motivo:
    description: 'Motivo del Restart'
    required: false
    default: ''
  test:
    description: 'Test'
    required: true
    default: 'false'
    
  qa:
    description: 'QA'
    required: true
    default: 'false'
  prod:
    description: 'Production'
    required: true
    default: 'false'

outputs:
  issueId:
    description: 'ID de la issue creada'
    value: ${{ steps.validate_format.outputs.issueId }}


runs:
  using: "composite"
  steps:

    - name: Validate Format
      id: validate_format
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const owner = context.repo.owner;
          const repo = context.repo.repo;

          // Numero de action ejecutada
          const actionNumber = context.runNumber;

          const title = `Restart Service${inputs.motivo ? ` - ${inputs.motivo}` : ''}`;
          const labels = ['restart-service', 'cicd'];

          const body = `

          ## Motivo
          ${inputs.motivo}

          ## Ambientes
          - Test: ${inputs.test}
          - QA: ${inputs.qa}
          - Prod: ${inputs.prod}


          ## Número de ejecución
          ${actionNumber}
          `;

        
          const { data: { id: issueId } } = await github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title,
            body,
            labels
          });

          core.setOutput('issueId', issueId);

    