name: "React CI"
description: "Realiza el lint, build, test and coverage"
inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ''
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'true' 
runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.matrix_version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: config npmrc file fontawesome 
      env:
        NPM_FONTAWESOME_TOKEN: ${{ inputs.fontawesome_token }}
      run: |
        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
        echo '//npm.fontawesome.com/:_authToken=$NPM_FONTAWESOME_TOKEN' >> .npmrc
      shell: bash
      if: ${{ inputs.fontawesome_token != '' }}
    - name: config npmrc file github packages 
      env:
        NPM_CUSTOMER_EXP_TOKEN: ${{ inputs.packages_token }}
      run: |
        echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '//npm.pkg.github.com/:_authToken=$NPM_CUSTOMER_EXP_TOKEN' >> .npmrc
      if: ${{ inputs.packages_token != '' }}
      shell: bash
    - name: Install dependency
      run: npm ci --no-audit
      shell: bash
    - name: Build
      run: npm run build --if-present
      shell: bash
      env:
        CI: false
    - run: npm test -- --coverage
      name: Unit tests
      shell: bash
      env:
        CI: false
      if: ${{ inputs.skip_test != 'true' }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: coverage
      if: ${{ inputs.skip_test != 'true' }}