name: "Configuración inicial de Copilot en la nube"
description: "Esta acción es un selector de configuración para Github copilot en la nube. Actualmente soporta .Net 6, .Net 8, .Net 10, CRA, Vite y Rsbuild. Se pueden agregar más configuraciones en el futuro."
branding:
  icon: 'dollar-sign'
  color: 'red'
author: "Architecture IT - Antony Fagundez"
  
inputs:
  github_token:
    description: Github Token
    required: true
  github_username: 
    description: github user 
    required: true
  workflow:
    required: true
    description: Workflow to run setup
  node_version:
    description: "version de node"
    required: false
    default: '22.x'
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  ## pnpm version
  pnpm_version:
    description: "version de pnpm"
    required: false
    default: '10'
  python_version:
    description: "version de python"
    required: false
    default: '3.12'

runs:
  using: "composite"
  steps:
    - name: Setup dotnet 6
      if: ${{ inputs.workflow == '.NET' }}
      uses: architecture-it/actions@dotnet-setup
      with:
        dotnet_version: '6.x'
        github_username: ${{ inputs.github_username }}
        github_token: ${{ inputs.github_token }}

    - name: Setup dotnet 8
      if: ${{ inputs.workflow == '.NET 8' }}
      uses: architecture-it/actions@dotnet-setup
      with:
        dotnet_version: '8.0.x'
        github_username: ${{ inputs.github_username }}
        github_token: ${{ inputs.github_token }}

    - name: Setup dotnet 10
      if: ${{ inputs.workflow == '.NET 10' }}
      uses: architecture-it/actions@dotnet-setup
      with:
        dotnet_version: '10.x'
        github_username: ${{ inputs.github_username }}
        github_token: ${{ inputs.github_token }}

    - name: Set up Node.js environment with Internal libraries
      if: ${{ inputs.workflow == 'CRA' || inputs.workflow == 'Vite' || inputs.workflow == 'Rsbuild' }}
      uses: architecture-it/actions@react-base-library
      with:
        matrix_version: ${{ inputs.node_version }}
        packages_token: ${{ inputs.github_token }}
        fontawesome_token: ${{ inputs.fontawesome_token }}
        pnpm_version: ${{ inputs.pnpm_version }}
        
    - name: Set up Node.js environment with Internal libraries
      if: ${{ inputs.workflow == 'Next.js' }}
      uses: architecture-it/actions@react-base-library
      with:
        matrix_version: ${{ inputs.node_version }}
        packages_token: ${{ inputs.github_token }}
        fontawesome_token: ${{ inputs.fontawesome_token }}
        pnpm_version: ${{ inputs.pnpm_version }}
        

    - name: Set up Python environment with Internal libraries
      if: ${{ inputs.workflow == 'Python' }}
      uses: architecture-it/actions@python-prebase
      with:
        version: ${{ inputs.python_version }}
        github_token: ${{ inputs.github_token }}
        github_username: ${{ inputs.github_username }}
