name: "SonarQube Pre-requisitos"
description: "Se realiza la configuración de los proyectos en sonarqube, se deben realizar a mano hasta que exista el endpoint de import from github"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
  sonar_key:
    description: "Key del repositorio"
    required: true
  alm_setting :
    description: "config alm github settings"
    required: false
    default: 'GitHubGLA'
  alm_setting_monorepo :
    description: "config alm github settings monorepo"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: "Create Project"
      run: |
        curl -X GET -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/qualitygates/project_status' -d projectKey=${{ inputs.sonar_key }} >> request.txt
      shell: bash 
    - name: "Show response"
      shell: bash
      run: cat request.txt
