name: "SonarQube Analyzer"
description: "Se realiza el análisis en sonarqube"
inputs:
  github_username:
    description: "usuario de github para autenticarse en los packages"
    required: false
    default: ''
  github_token:
    description: "token del usuario con permisos de lectura en packages"
    required: false
    default: ''
  workdir_src:
    description: "directorio donde se encuentra el project a compilar DEFAULT: ./"
    required: false
    default: './'
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./"
    required: false
    default: './'
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
  sonar_key:
    description: "Key del repositorio "
    required: true
  skip_test: 
    description: "Omite el analisis de test"
    required: false
    default: 'false'
  version:
    description: "version de lenguaje, ej 3.7, 3.8..."
    required: false
    default: '3.8'
runs:
  using: "composite"
  steps:
    - name: "Create Project"
      run: |
        curl -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/projects/create' -d name=${{ inputs.sonar_key }} -d project=${{ inputs.sonar_key }}
      shell: bash 
    - name: "Rename Branch default"
      run: |
        curl -s -X POST -u ${{ inputs.sonar_token }}: ${{ inputs.sonar_url }}/api/project_branches/rename -d project={{ inputs.sonar_key }} -d name=${{ github.event.repository.default_branch }} -D- -o /dev/null -w %{http_code} > http.txt
      shell: bash 
    - name: "Analisis rename branch"
      id: rename
      run: |
        cat http.txt
        if grep -q "204" http.txt;
        then
          echo "Todo OK"
          echo "::set-output name=OUTPUT::0"
        else 
          echo "la branch no se seteo por defecto se eliminara la branch para definir la nueva por defecto"
          echo "::set-output name=OUTPUT::1"
        fi
      shell: bash
    - name: "Delete and Rename branch"
      run: |
          curl -X POST -u ${{ inputs.sonar_token }}: ${{ inputs.sonar_url }}/api/project_branches/delete -d project={{ inputs.sonar_key }} -d branch=${{ github.event.repository.default_branch }}
          curl -X POST -u ${{ inputs.sonar_token }}: ${{ inputs.sonar_url }}/api/project_branches/rename -d project={{ inputs.sonar_key }} -d name=${{ github.event.repository.default_branch }}
      if: steps.rename.outputs.OUTPUT == 1
      shell: bash
 #   - name: "Setting binding github"
 #     run: |
 #       curl -X POST -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/projects/create' -d name=${{ inputs.sonar_key }} -d project=${{ inputs.sonar_key }}
 #     shell: bash 
    - name: "Create Project"
      run: echo ${{ github.repo.name }}
      shell: bash
