name: "SonarQube Python Analyzer"
description: "Se realiza el análisis en SonarQube para proyectos Python"
inputs:
  sonar_url: 
    description: "URL de SonarQube"
    required: true
  sonar_token: 
    description: "Token de SonarQube"
    required: true
  sonar_key:
    description: "Clave del repositorio en SonarQube"
    required: true
  version:
    description: "Versión de Python, ej. 3.7, 3.8..."
    required: true
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false'
    # Directories
  workdir_src:
    description: "directorio donde se encuentra el project a compilar DEFAULT: ./"
    required: false
    default: './'
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./"
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - name: Download code coverage results
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
        path: ${{ inputs.workdir_test }}
      if: ${{ inputs.skip_test != 'true' }}

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: ${{ inputs.workdir_src }}
        args: >
          -Dsonar.projectKey=${{ inputs.sonar_key }}
          -Dsonar.verbose=true
          -Dsonar.python.version=${{ inputs.version }}
          -Dsonar.python.coverage.reportPaths=coverage.xml
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_url }}
