name: "Dotnet build and test"
description: "Realiza el Restore, build y test"
inputs:
  workdir_src:
    description: "directorio donde se encuentra el cproj a compilar DEFAULT: ./"
    required: false
    default: './'
  workdir_test:
    description: "directorio donde se encuentra los test DEFAULT: ./"
    required: false
    default: './'
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - run: go version
      shell: bash

    - name: Build
      run: go build -v ${{ inputs.workdir_src }}/main.go
      shell: bash
        
    - name: Test
      run: |
        go test ${{ inputs.workdir_test }} ./... -coverprofile=coverage.out
      shell: bash
      if: ${{ inputs.skip_test != 'true' }}

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ./coverage.out
      if: ${{ inputs.skip_test != 'true' }}
