name: 'Validate Status Project (SonarQ)'
description: 'Unique step to Validate Status Project (SonarQ)'
inputs:
  sonar_url:
    description: "Url SonarQube"
    required: true
  sonar_token:
    description: "Token de acceso SonarQube"
    required: true
  projectKey:
    description: "Project Key SonarQube"
    required: false
    default: ""
  branch:
    description: "Branch SonarQube"
    required: false
    default: "main"

runs:
  using: "composite"
  steps:
    - name: Validate
      shell: bash
      run: |
        status=$(curl -X GET -u ${{ inputs.sonar_token }}: '${{ inputs.sonar_url }}/api/qualitygates/project_status?projectKey=${{ inputs.projectKey }}&branch=${{ inputs.branch }}' | jq '.projectStatus.status')
        
        if [[ $status != '"OK"' ]]; then
          echo "❌ SonarQube Quality Gate failed for Project '${{ inputs.projectKey }}' in branch '${{ inputs.branch }}'. Project Status: $status"
          if [[ $status == ''"NONE""']]; then
            echo "❗ Appears that is no quality gate associated with the project."
          fi
          exit 1
        fi
        echo "✅ SonarQube Quality Gate passed for Project '${{ inputs.projectKey }}' in branch '${{ inputs.branch }}'."
