name: "React Native CI"
description: "Realiza el lint, build, test and coverage"
inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ''
  sdk_platform:
    required: false
    description: "SDK Platform"
    default: "31"
  build_tools: 
    required: false
    description: "Build tools"
    default: "31.0.0"
  sdk_tools:
    required: false
    description: "SDK Build tools"
    default: "7583922_latest"
  emulator_version:
    required: false
    description: "Emulator version"
    default: "30.7.5"

runs:
  using: "composite"
  
  steps:
    - name: Use Node.js ${{ inputs.matrix_version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: config npmrc file fontawesome 
      run: |
        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
        echo '//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome_token }}' >> .npmrc
      shell: bash
      if: ${{ inputs.fontawesome_token != '' }}
    - name: config npmrc file github packages of company
      run: |
        echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '//npm.pkg.github.com/:_authToken=${{ inputs.packages_token }}' >> .npmrc
      shell: bash
      if: ${{ inputs.packages_token != '' }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Android SDK and build tools
      uses: android-actions/setup-android-sdk@v2
      with:
        sdk-platform: ${{ inputs.sdk_platfomr }}
        build-tools: ${{ inputs.build_tools }}
        sdk-tools: ${{ inputs.sdk_tools }}
        emulator-version: ${{ inputs.emulator_version }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash


