name: "Validate PR Format"
description: "Realiza la validacion del formato del PR"
inputs:
  github_token:
    description: Github Token
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get Name of commits title and branch name
      id: get_pr_name
      run: |
        pr_name=$(jq -r .pull_request.title $GITHUB_EVENT_PATH)
        branch_name=$(jq -r .pull_request.head.ref $GITHUB_EVENT_PATH)
        commit_messages=$(git log --pretty=format:"%s" $branch_name)
        echo "pr_name=$pr_name" >> $GITHUB_ENV
        echo "branch_name=$branch_name" >> $GITHUB_ENV
        echo "commit_messages=$commit_messages" >> $GITHUB_ENV
      shell: bash

    - name: Validate Format
      id: validate_format
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { pr_name, branch_name, commit_messages } = process.env;
          // const { valid, message } = validateFormat(pr_name, branch_name, commit_messages);


          const regexOfIssue = /^.*?[A-Z0-9-]+.*$/g;
          const regexConventionCommit = /^(feat|fix)\:\s.*$/g;

          const branchName = branch_name.replace(/refs\/heads\//, '');


          // JIRA VALIDATIONS
          const isValidTitleOfPRForJira = pr_name.match(/^(feat|fix)\([A-Z0-9-]+\)\:\s.*$/);

          const isValidBranchNameForJira = branchName.match(regexOfIssue);`
          
          const isValidAnyCommitMessagesForJira = commit_messages.split('\n').some((message) => {
            return message.match(regexOfIssue);
          });`

          const willTriggerNewVersion = pr_name.match(regexConventionCommit);

          const anyJiraIntegrationValid = isValidTitleOfPRForJira || isValidBranchNameForJira || isValidAnyCommitMessagesForJira;

          const body = `

          
          <details>
          <summary>Conventional Commit ${willTriggerNewVersion ? ':white_check_mark:' : ':x:'}</summary>
          
          - Will trigger new version: ${willTriggerNewVersion ? ':heavy_check_mark:' : ':exclamation:'}.
            if you want to trigger a new version, you must use the following format: (feat|fix): message. See more in [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
          </details>
          <details>
            <summary>Jira Integration ${anyJiraIntegrationValid ? ':white_check_mark:' : ':x:'}</summary>

            - Title of PR: ${isValidTitleOfPRForJira ? ':heavy_check_mark:' : ':exclamation:'}
            - Branch Name: ${isValidBranchNameForJira ? ':heavy_check_mark:' : ':exclamation:'}
            - Some Commit Messages: ${isValidAnyCommitMessagesForJira ? ':heavy_check_mark:' : ':exclamation:'}
          </details>
          `;


            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });

    