name: "Release Dot Net"
description: "Realiza el release basado en los commits y conventional commit"
inputs:
  github_token:
    description: Github Token
    required: true
  branches:
    description: configuration to latest release and prerelease
    default: '["cicd", { name: "main", prerelease: "development" }]'
    required: false
  csproj_path: 
    description: paths related to csproj files. Admits glob patterns, Found all in
    default: "src/Api/"
    required: false
  pack_arguments:
    description: arguments passed to pack
    default: '["--skip-duplicate bin/Release/*.nupkg"]'
    required: false
  github_username: 
    description: github user 
    required: true


runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Add NuGet sources
      run: |
        dotnet nuget locals -c all       
        dotnet nuget add source https://nuget.pkg.github.com/architecture-it/index.json --name github -u ${{ inputs.github_username }} -p ${{ inputs.github_token  }} --store-password-in-clear-text
      shell: bash
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Write configuration file
      shell: bash
      run: |
        echo 'module.exports = { plugins: ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/github",["semantic-release-dotnet",{paths: ["${{ inputs.csproj_path }}**.csproj"] }], ["@semantic-release/exec",{  "prepareCmd": "dotnet restore && dotnet build --configuration 'Release' && dotnet pack -c 'Release'", "publishCmd": "dotnet nuget push --source github --api-key ${{ inputs.github_token }} --skip-duplicate bin/Release/*.nupkg" ,},], ["@semantic-release/git",{  message: "Release <%= nextRelease.version %> [skip ci]",  assets: ["README.md"],},],],branches: ${{ inputs.branches }} }' >> release.config.js
    - name: Install dependencies
      run: npm i --no-save @semantic-release/git @semantic-release/github semantic-release-dotnet @semantic-release/exec
      shell: bash
    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
        NUGET_PUSH_URL: "https://nuget.pkg.github.com/architecture-it/index.json"
        NUGET_TOKEN: ${{ inputs.github_token }}
      working-directory: ${{ inputs.csproj_path }}
      run: npx semantic-release
      shell: bash
    