name: "Sonar Analizer React Native"
description: "Realiza el análisis de sonarqube para React Native (Javascript/Typescript)"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
  sonar_key:
    description: "Key del repositorio"
    required: true
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
runs:
  using: "composite"
  steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
        if: ${{ inputs.skip_test != 'true' }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
          SONAR_HOST_URL: ${{ inputs.sonar_url }}
          LC_ALL: "ru_RU.UTF-8"
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar_key }}
            -Dsonar.exclusions=.github/**,.vscode/**,android/**,assets/**,build/**,ios/**,node_modules/**,scripts/**,**/__mocks__/**,*.config.js,*rc.js,src/**/styles.js,src/**/styles.ts,src/**/*.styles.js,src/**/*.styles.ts,**/*.stories.tsx,**/*.stories.jsx,src/icons/**,stories/**
            -Dsonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx
            -Dsonar.javascript.lcov.reportPaths=**/coverage/lcov.info