name: "Release npm"
description: "Realiza el release basado en los commits y conventional commit"
inputs:
  publish:
    description: "Publish to internal modules"
    required: false
    default: "true"
  github_token:
    description: Github Token
    required: true
  branches:
    description: configuration to latest release and prerelease
    default: '["main", { name: "development", prerelease: "development" }]'
    required: false
  pkg_root:
    description: Root of package by default is dist following the template of libraries
    default: 'dist'
    required: false
  node_version:
    description: Node version
    default: '20.x'
    required: false

runs:
    - name: Write configuration file
      shell: bash
      run: |
        echo 'module.exports = { "extends": "semantic-release-monorepo", pkgRoot: "${{ inputs.pkg_root }}", plugins: ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md" }], ["@semantic-release/npm",{  "npmPublish": ${{ inputs.publish }},}],"@semantic-release/github",["@semantic-release/exec",{  prepareCmd: "npx replace-json-property package.json version ${nextRelease.version}",},],["@semantic-release/git",{  message: "Release <%= nextRelease.version %> [skip ci]",  assets: ["package.json", "CHANGELOG.md"],},],],branches: ${{ inputs.branches }} }' >> release.config.cjs
    - name: Release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GH_TOKEN: ${{ inputs.github_token }}
      run: pnpm exec semantic-release
      shell: bash
