name: "React CI"
description: "Realiza el lint, build, test and coverage"
inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ''
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
  ci:
    description: "Esta variable forza el chequeo del linter y en caso de fallas rompe el flujo"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Get package manager of Repo
      run: |
        if [ -f "yarn.lock" ]; then 
          echo "name=yarn" >> $GITHUB_OUTPUT
        elif [ -f "package-lock.json" ]; then 
          echo "name=npm" >> $GITHUB_OUTPUT 
        elif [ -f pnpm-lock.yaml ]; then 
          echo "name=pnpm" >> $GITHUB_OUTPUT 
        else 
          echo "name=npm" >> $GITHUB_OUTPUT  
        fi
      id: package_manager
      shell: bash
      # Use default with cache
    - name: Use pnpm Setup
      uses: pnpm/action-setup@v2
      with:
        version: 6.32.9
      if: ${{ steps.package_manager.outputs.name == 'pnpm' }}
    - name: Use Node.js ${{ inputs.matrix_version }} - Cache ${{ steps.package_manager.outputs.name }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ steps.package_manager.outputs.name }}
    - name: config npmrc file fontawesome 
      run: |
        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
        echo '//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome_token }}' >> .npmrc
      shell: bash
      if: ${{ inputs.fontawesome_token != '' }}
    - name: config npmrc file github packages of company
      run: |
        echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '@operations-innovation:registry=https://npm.pkg.github.com/' >> .npmrc
        echo '//npm.pkg.github.com/:_authToken=${{ inputs.packages_token }}' >> .npmrc
      shell: bash
      if: ${{ inputs.packages_token != '' }}
    - name: Setup .yarnrc.yml (Yarn 2)
      run: |
        yarn config set npmScopes.architecture-it.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.architecture-it.npmAlwaysAuth true
        yarn config set npmScopes.architecture-it.npmAuthToken ${{ inputs.packages_token }}
        yarn config set npmScopes.customer-experience.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.customer-experience.npmAlwaysAuth true
        yarn config set npmScopes.customer-experience.npmAuthToken ${{ inputs.packages_token }}
        yarn config set npmScopes.operations-innovation.npmRegistryServer "https://npm.pkg.github.com"
        yarn config set npmScopes.operations-innovation.npmAlwaysAuth true
        yarn config set npmScopes.operations-innovation.npmAuthToken ${{ inputs.packages_token }}
      shell: bash
      if: ${{ steps.package_manager.outputs.name == 'yarn' }}
    - name: Install dependencies
      run: |
        if [ -f yarn.lock ]; then 
          echo "yarn.lock file founded. Installing using yarn" && yarn --frozen-lockfile
        elif [ -f package-lock.json ]; then
          echo "package-lock file founded. Installing using npm" && npm ci --no-progress --loglevel error
        elif [ -f pnpm-lock.yaml ]; then
          echo "pnpm-lock lock file founded. Installing using pnpm" && yarn global add pnpm && pnpm install --frozen-lockfile
        else 
          echo "Lockfile not found. Installing from scratch" && npm install
        fi
      shell: bash
    - name: Lint
      run: ${{ steps.package_manager.outputs.name }} run lint --if-present
      shell: bash
    - name: Build
      run: ${{ steps.package_manager.outputs.name }} run build
      shell: bash
      env:
        CI: ${{ inputs.ci == 'true' }}
    - run: ${{ steps.package_manager.outputs.name }} test -- --coverage --runInBand
      name: Unit tests
      shell: bash
      env:
        CI: ${{ inputs.ci == 'true' }}
      if: ${{ inputs.skip_test != 'true' }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage
      if: ${{ inputs.skip_test != 'true' }}
