name: "SonarQube PHP Analyzer"
description: "Se realiza el análisis en SonarQube para proyectos PHP"
inputs:
  sonar_url: 
    description: "URL de SonarQube"
    required: true
  sonar_token: 
    description: "Token de SonarQube"
    required: true
  sonar_key:
    description: "Clave del repositorio en SonarQube"
    required: true

runs:
  using: "composite"
  steps:
      - name: CI ok
        shell: bash
        run: 'echo OK'
