name: "Sonar Analizer Go"
description: "Realiza el análisis de sonarqube para Go"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
  sonar_key:
    description: "Key del repositorio"
    required: true
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: test
        if: ${{ inputs.skip_test != 'true' }}
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
          SONAR_HOST_URL: ${{ inputs.sonar_url }}
          LC_ALL: "ru_RU.UTF-8"
        with:
          args: >
            -Dsonar.projectKey=${{ inputs.sonar_key }}
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.test.exclusions=**/*__constructor.go
            -Dsonar.go.coverage.reportPaths=**/coverage.out
            -Dsonar.exclusions=**/*__constructor.go
