name: "SonarQube HTML Analyzer"
description: "Se realiza el análisis en SonarQube para proyectos HTML"
inputs:
  sonar_url: 
    description: "URL de SonarQube"
    required: true
  sonar_token: 
    description: "Token de SonarQube"
    required: true
  sonar_key:
    description: "Clave del repositorio en SonarQube"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download code coverage results
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
        path: ${{ inputs.workdir_test }}
      if: ${{ inputs.skip_test != 'true' }}

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: ./src
        args: >
          -Dsonar.projectKey=${{ inputs.sonar_key }}
          -Dsonar.coverage.exclusions=**/*
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_url }}
