name: "SonarQube Python Analyzer"
description: "Se realiza el análisis en SonarQube para proyectos Python"
inputs:
  sonar_url: 
    description: "URL de SonarQube"
    required: true
  sonar_token: 
    description: "Token de SonarQube"
    required: true
  sonar_key:
    description: "Clave del repositorio en SonarQube"
    required: true
  version:
    description: "Versión de Python, ej. 3.7, 3.8..."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install coverage  # Instalar coverage para generar informes
      shell: bash  # Especificar el shell

    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover -s test/. -p "*.py"
        coverage report
        coverage xml  # Generar el informe en formato XML
      shell: bash  # Especificar el shell

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml  # Archivo de informe de cobertura en formato XML

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ inputs.sonar_key }}
          -Dsonar.verbose=true
          -Dsonar.python.version=${{ inputs.version }}
          -Dsonar.python.coverage.reportPaths=coverage.xml  # Ruta del informe de cobertura
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_url }}

# name: "SonarQube Python Analyzer"
# description: "Se realiza el análisis en sonarqube para proyectos python"
# inputs:
#   sonar_url: 
#     description: "url sonarqube"
#     required: true
#   sonar_token: 
#     description: "token sonarqube"
#     required: true
#   sonar_key:
#     description: "Key del repositorio"
#     required: true
#   version:
#     description: "version de lenguaje, ej 3.7, 3.8..."
#     required: true
# runs:
#   using: "composite"
#   steps:
#     - name: SonarQube Scan
#       uses: sonarsource/sonarqube-scan-action@master
#       env:
#         SONAR_TOKEN: ${{ inputs.sonar_token }}
#         SONAR_HOST_URL: ${{ inputs.sonar_url }}
#         LC_ALL: "ru_RU.UTF-8"
#       with:
#         projectBaseDir: .
#         args: >
#           -Dsonar.projectKey=${{ inputs.sonar_key }}
#           -Dsonar.verbose=true
#           -Dsonar.python.version=${{ inputs.version }}
