name: "Sync topics"
description: "Realiza el update/sync de los topics de un repositorio"
inputs:
  github_token:
    description: "token github"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      with:
        retries: 3
        debug: true
        github-token: ${{ inputs.github_token }}
        script: |
          const topics = '${{ github.event.inputs.topics }}';
          const { data: { names: actualTopics } } = await github.rest.repos.getAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
          });
          core.info(`Actual topics: ${actualTopics.join(', ')}`);

          const newTopics = topics.split(',').map(topic => topic.trim());
          core.info(`New topics: ${newTopics.join(', ')}`);

          const finalTopics = actualTopics.concat(newTopics);

          if(finalTopics === 0) {
              core.info(`Not topics to sync`);
              return;
          }

          await github.rest.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: finalTopics
          });

          core.info(`Topics sync: ${finalTopics.join(', ')}`);
