name: "React CI"
description: "Realiza el lint, build, test and coverage"
inputs:
  matrix_version:
    description: "matrix de pruebas node"
    required: true
  fontawesome_token: 
    description: "token de fontawesome"
    required: false
    default: ''
  packages_token:
    description: "token github para autenticarse en packages"
    required: false
    default: ''
  skip_test:
    description: "permite skipear los procesos de testing"
    required: false
    default: 'false' 
  ci:
    description: "Esta variable forza el chequeo del linter y en caso de fallas rompe el flujo"
    required: false
    default: 'false'
  skip_lint:
    description: "permite skipear los procesos de linter y formateo"
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Get package manager and install command
      run: |
        if [ -f "yarn.lock" ]; then 
          echo "name=yarn" >> $GITHUB_OUTPUT 
          echo "command=yarn --frozen-lockfile" >> $GITHUB_OUTPUT 
        elif [ -f "package-lock.json" ]; then 
          echo "name=npm" >> $GITHUB_OUTPUT 
          echo "command=npm ci --no-progress --loglevel error" >> $GITHUB_OUTPUT 
        elif [ -f pnpm-lock.yaml ]; then 
          echo "name=pnpm" >> $GITHUB_OUTPUT 
          echo "command=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT 
        else 
          echo "name=notfound" >> $GITHUB_OUTPUT
        fi
      id: package_manager
      shell: bash
    - name: validate 'Lockfile'
      if: ${{ steps.package_manager.outputs.name == 'notfound' }}
      run: |
        echo "El código debe contener algún archivo de lockfile ('package-lock.json', 'yarn.lock' o 'pnpm-lock.yaml')."
        echo "Asegurate de subirlo."
        echo "ERROR: Falta archivo lockfile. Ver más en https://architecture-it.github.io/docs/Platform/Front/#manejo-de-dependencias"
        exit 1
      shell: bash    
      # Use default with cache
    - name: Use pnpm Setup
      uses: pnpm/action-setup@v2
      with:
        version: 8
      if: ${{ steps.package_manager.outputs.name == 'pnpm' }}
    - name: Use Node.js ${{ inputs.matrix_version }} - Cache ${{ steps.package_manager.outputs.name }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: ${{ steps.package_manager.outputs.name }}
    - name: Generate .npmrc file
      uses: architecture-it/actions@generate-npmrc
      with:
        npm_token: ${{ inputs.packages_token }}
        font_awesome_key: ${{ inputs.fontawesome_token }}
      if: ${{ inputs.packages_token != '' }}
    - name: Install dependencies
      run: ${{ steps.package_manager.outputs.command }}
      shell: bash
    - name: "Read Package Json"
      uses: actions/github-script@v6
      id: package
      with:
        script: |
          const fs = require('fs')
          try {
            const jsonString = fs.readFileSync('./package.json', 'utf8');
            const json = JSON.parse(jsonString);
            const lint = json.scripts?.lint || '';
            const test = json.scripts?.test || '';

            return { lint, test }
          } catch(err) {
            core.error("Error while reading or parsing the 'package.json' file")
            core.setFailed(err.message)
          }
    - name: Lint
      run: ${{ steps.package_manager.outputs.name }} run lint
      shell: bash
      if: ${{ inputs.skip_lint != 'true' && fromJson(steps.package.outputs.result).lint != '' }}
    - name: Build
      run: ${{ steps.package_manager.outputs.name }} run build
      shell: bash
      env:
        CI: ${{ inputs.ci == 'true' }}
    - name: Get extra slash
      run: |
        if [ ${{ fromJson(steps.package.outputs.result).test == 'jest' }} ]; then
          echo "extra_slash=" >> $GITHUB_OUTPUT
        else
          echo "extra_slash=--" >> $GITHUB_OUTPUT
        fi
      id: extra_slash
      shell: bash
    - name: Get tests flags
      run: |
        if [ -f package.json ]; then
          if grep -q vitest package.json; then
            echo "tests_flags=" >> $GITHUB_OUTPUT
          else
            echo "tests_flags=--json --runInBand --testLocationInResults --outputFile=report.json" >> $GITHUB_OUTPUT
          fi
        fi
      id: flags
      shell: bash
    - name: Unit tests
      run: ${{ steps.package_manager.outputs.name }} run test ${{ steps.extra_slash.outputs.extra_slash }} --coverage ${{ steps.flags.outputs.tests_flags }}
      shell: bash
      env:
        CI: ${{ inputs.ci == 'true' }}
      if: ${{ inputs.skip_test != 'true' }}
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: coverage
      if: ${{ inputs.skip_test != 'true' }}
