name: "SonarQube Python Analyzer"
description: "Se realiza el análisis en sonarqube para proyectos python"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
runs:
  using: "composite"
  steps:
    - name: Key Repository
      id: variables
      uses: actions/github-script@v5
      with:
        script: |
          const name = context.repo.repo
          const organization = context.repo.owner
          core.exportVariable('KEY_REPOSITORY', `${organization}_${name}`)
    # Sonar Qube
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ inputs.sonar_token }}
        SONAR_HOST_URL: ${{ inputs.sonar_url }}
        LC_ALL: "ru_RU.UTF-8"
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ env.KEY_REPOSITORY }}
          -Dsonar.verbose=true
          -Dsonar.python.version=3.7, 3.8, 3.9
