name: "Sonar Analizer Go"
description: "Realiza el análisis de sonarqube para Go"
inputs:
  sonar_url: 
    description: "url sonarqube"
    required: true
  sonar_token: 
    description: "token sonarqube"
    required: true
runs:
  using: "composite"
  steps:
      - name: Key Repository
        id: variables
        uses: actions/github-script@v5
        with:
          script: |
            const name = context.repo.repo
            const organization = context.repo.owner
            core.exportVariable('KEY_REPOSITORY', `${organization}_${name}`)
      - name: Download code coverage results
        uses: actions/download-artifact@v1
        with:
          name: code-coverage-report
          path: test
      - run: |
          cat test/coverage.out
          cat test/report.json
        shell: bash 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
          SONAR_HOST_URL: ${{ inputs.sonar_url }}
          LC_ALL: "ru_RU.UTF-8"
        with:
          args: >
            -Dsonar.projectKey=${{ env.KEY_REPOSITORY }}
            -Dsonar.tests=.
            -Dsonar.test.inclusions=**/*_test.go
            -Dsonar.go.coverage.reportPaths=**/coverage.out
            -Dsonar.go.tests.reportPaths=**/report.json