name: "Generate .npmrc"
description: "Genera el archivo de configuración para los paquetes"
inputs:
  npm_token:
    description: Github Token
    required: true
  font_awesome_key:
    description: Font Awesome key 
    required: true
  add_pnpm_flags:
    description: Add defaults flags to pnpm works correctly
    default: "true"
    required: false

runs:
  using: "composite"
  steps:
  - name: Append or generate organizations config
    run: |
      echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
      echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
      echo '@operations-innovation:registry=https://npm.pkg.github.com/' >> .npmrc
      echo '//npm.pkg.github.com/:_authToken=${{ inputs.npm_token }}' >> .npmrc
      echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
      echo '//npm.fontawesome.com/:_authToken=${{ inputs.font_awesome_key }}' >> .npmrc
    shell: bash
  - name: Add flags importants to pnpm
    run: echo 'enable-pre-post-scripts=true' >> .npmrc
    shell: bash
    if: ${{ inputs.add_pnpm_flags }}
