name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    branches:
      - validate-yaml
  push:
    branches:
      - validate-yaml

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: config npmrc file github packages of company
        run: |
          echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
          echo '//npm.pkg.github.com/:_authToken=${{ secrets.ARQUITECTURA_DEPLOY }}' >> .npmrc
        shell: bash
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    env:
      NODE_DEBUG: http
    steps:
      - uses: actions/checkout@v3
      - name: list files
        run: ls
        shell: bash
      - uses: ./
        with:
          jsonSchemaFile: "https://gladynamics.blob.core.windows.net/arquitectura/cicd-andreani.json"
          yamlFiles: "./test/values.yml"
